### ISSUE TITLE
Several controls on sample application are invisible

### ISSUE THREAD

**Issue by Symbai** [iNKORE-Public/UI.WPF.Modern#39]
**Describe the bug**
For example AnimatedIcon:
![image](https://github.com/iNKORE-Public/UI.WPF.Modern/assets/14368203/e0ed2a38-aea5-432e-a832-830670d8640b)

But also AnimatedVisualPlayer, Animated Interop, 

**To Reproduce**
Open sample app click on animated icon

**Expected behavior**
Expect to see an animatedicon control sample

**Desktop (please complete the following information):**
 - OS: Win 11

**Comment by NotYoojun** [comment]
This is because we don't have any control called `AnimatedIcon`. This sample app is ported from the WinUI Gallery.
Just ignore these stuff. (PS: Any controls that is displayed gray in the left NavigationView is not implemented)
We may remove these blank pages in free time. This is not really a big problem
